format_version: 3
pipelines:
  docker-node-dojo:
    group: platform
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    secure_variables:
      VAULT_TOKEN: "AES:lv1jmQn6vqy17aFPfN0s6Q==:VZ/OhqN6uVYeteqa/4hvoFe6GsaB6ibYULslN1MM3Uw="
    stages:
      - build:
          clean_workspace: true
          jobs:
            docker_image:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: image/imagerc
                    destination:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build
      - itest:
          clean_workspace: true
          jobs:
            end_user:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: docker_image
                    is_file: yes
                    source: imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest
      - release:
          clean_workspace: true
          jobs:
            code:
              # this could run on elastic go agent, but since all the jobs
              # are run here on docker_builder, let's run this job there too
              resources:
                - docker_builder
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            image:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: docker_image
                    is_file: yes
                    source: imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
